name = "dantheme"
license = "MIT"
description = "theme for my webpage"
homepage = "allokkio.net"
tags = ["personal", "starter"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Daniel Klotz"
